### ISSUE TITLE
Server config checks shouldn't be required in offline mode

### ISSUE THREAD

**Issue by wk9874** [simvue-io/python-api#672]
In offline mode, you are still required to enter the server URL and token (lines 216 - 220 of `simvue/config/user.py`) - these shouldnt be required in offline mode.

Even if you do specify these, the code currently still performs a check of their validity in `check_valid_server` - this will fail in the case of no internet connection. It currently uses `mode` to define when to skip this check, but that parameter is only defined in the higher level API, not the lower level one. Meaning if you do eg `Tag.new(offline=True)`, it wont pop 'mode' in line 154 of `base.py`, and therefore will treat it as an online run.

**Comment by wk9874** [comment]
```
from simvue.api.objects.tag import Tag

import time
tag = Tag(offline=True)
tag.new(name="my_tag_2")
```
Code which provokes the issue ^

**Comment by kzscisoft** [comment]
@wk9874 is this resolved now?

**Comment by wk9874** [comment]
No this is not fixed

Running in offline mode with no simvue.toml file gives

```
WARNING:simvue.config.user:No config file found, checking environment variables
Traceback (most recent call last):
  File "/home/wk9874/Documents/simvue/python-api/test.py", line 7, in <module>
    tag = Tag(offline=True)
  File "/home/wk9874/Documents/simvue/python-api/simvue/api/objects/base.py", line 157, in __init__
    self._user_config = SimvueConfiguration.fetch(**_config_args)
  File "/home/wk9874/Documents/simvue/python-api/simvue/utilities.py", line 281, in wrapper
    return class_func(self, *args, **kwargs)
  File "/home/wk9874/Documents/simvue/python-api/simvue/config/user.py", line 216, in fetch
    raise RuntimeError("No server URL was specified")
RuntimeError: No server URL was specified
```

The server URL and token should not be required for offline runs

Also see https://github.com/simvue-io/python-api/issues/684

**Comment by wk9874** [comment]
Does work, but spams these messages to console:

```
WARNING:simvue.config.user:No config file found, checking environment variables
```

Would like to fix that...

**Comment by wk9874** [comment]
Changed that to a debug level message in v2.0.0a2

**Comment by wk9874** [comment]
Can now run offline mode with no internet connection without seeing any errors / warnings
